# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f191b3f97e1a89f9f03ccd58c5799b9bdd87c500775bfe5d9c830684f30ae4ae8953bf7d868b2584d58f2ffe9b32a821a6e11909e4ec47605cd0a8dc9cc76ae

test:
  secret_key_base: f23aacbc9d9fb0621bacd98aaaffb650e75855727274a90e736fe388b65ae6faaf60308dd0d25cedca02e8802978c2d9774fab97cf88e708b8bfd975bc3e6d74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
